name: Sync to Gitee

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa

    - name: Set up Git
      run: |
        git config --global user.name '${{ secrets.GITEE_USERNAME }}'
        git config --global user.email '${{ secrets.GITEE_EMAIL }}'

    - name: Mirror repository to Gitee
      env:
        GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
      run: |
        git remote add gitee git@gitee.com:comhub/sople.net.git
        git push --mirror gitee
